# Generated by Django 3.2.6 on 2022-01-22 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=26)),
                ('tag', models.CharField(default='none', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('photo', models.ImageField(default='contest_art/default.png', upload_to='contest_art')),
                ('brief_post', models.TextField(blank=True, null=True)),
                ('post', models.TextField(blank=True, null=True)),
                ('cash_vote', models.BooleanField(default=False)),
                ('vote_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('category', models.CharField(blank=True, max_length=30, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('photo', models.ImageField(default='contestant_art/default.png', upload_to='contestant_art')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('brief_post', models.TextField(blank=True, null=True)),
                ('post', models.TextField(blank=True, null=True)),
                ('votes', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participating_contest', to='contest.contest')),
            ],
        ),
    ]
